title: writing-functions-javascript
hero_image: images/banner.png
description: Writing functions in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Writing and Calling functions
